### ISSUE TITLE
Especificação do protocolo de sinalização do jogo (versão v0.1) 

### ISSUE THREAD

**Issue by rafafonsecaa** [JeanMotaa/SMU---LabirintoCego#1]

**Comment by rafafonsecaa** [comment]
Entrega 1(12/05/22.1):

Em relação ao protocolo de sinalização, há os seguintes requisitos funcionais:

- RF0: Implementar o modelo de requisição-resposta para atender ao modelo Web.

- RF1: Ser agnóstico em relação aos protocolos inferiores (Aplicação/Apresentação/Sessão e Transporte) no que se refere a garantia de entrega. Portanto, para cada requisição deve haver uma resposta.

- RF2: Prever respostas positivas e negativas para as requisições, permitindo o jogador/usuário decidir se quer atender as requisições de outros jogadores para participar, por exemplo, de sessões de mídia.

- RF3: Prever a organização dos jogadores em salas ou namespaces para uso concorrente de um mesmo serviço com ambientes isolados entre si.

- RF4: Prever que cada jogador tenha um identificador único, o qual pode ser um valor aleatório (hash criado dinamicamente, por exemplo) ou fixado pelo próprio usuário, como por exemplo uma URI conhecida. Para este último, será preciso, adicionalmente, implementar esquema interno ou externo de autenticação (Oauth 2.0, por exemplo).

- RF5: Prever a criação e destruição de salas ou namespaces. Opcionalmente, pode haver administração das salas para os criadores, e para este caso é preciso definir pelo menos dois níveis de permissão por sala (criador, outros). Além disso, é opcional a persistência de salas no serviço (estado, listas de permissão ou bloqueio de jogadores etc.).

- RF6: Com a organização de salas ou namespaces, prever sistema de presença de usuários para apresentação aos demais, de forma que seja possível o convite posterior.

- RF7: Prever convites diretos entre jogadores, na modalidade PVP (player-versus-player), de forma análoga ao unicast.

- RF8: Prever convites entre um jogador e todos os demais de uma determinada sala ou namespace, de forma análoga ao multicast (seleção de n jogadores dentro todos do serviço). Ou seja, atender a comunicação entre 2 ou mais jogadores.

- RF9: Prever o encapsulamento de um protocolo de negociação e descrição de mídia para que o navegador consiga negociar caminhos (Rede, Transporte), mídias e codecs (Aplicação).

E requisitos não funcionais:

- RNF1: Estar de acordo com os fundamentos da disciplina de Projeto de Protocolos.

- RNF2: Ser um protocolo baseado em texto e legível (para humanos).

**Comment by rafafonsecaa** [comment]
**Requisições Cliente - Servidor:**

**CASO 1:** Cliente registrando presença no ambiente → Servidor permite

Cliente: "entrar:nome:sala"
Servidor: "OK:TOKEN:codigo"

**CASO 2:** Cliente registrando presença no ambiente(acesso pela primeira vez ou tentando reconectar) → Servidor não permite por algum erro no nome do usuário (usuário duplicado ou incorreto)

Cliente: "entrar:nome:sala"
Servidor: "nOK:codigo"

**CASO 3:** Cliente registrando presença no ambiente → Servidor não permite por lotação da sala

Cliente: "entrar:nome:sala"
Servidor: "nOK:codigo"

**CASO 4:** KeepAlive → Mensagem recorrente para verificar se o link entre os dois está operando

Cliente: "alive:TOKEN"
Servidor: "OK:codigo"

**CASO 5:** Cliente saiu do ambiente → Conexão encerrada 

Cliente: "close:TOKEN"
Servidor: "OK:codigo"

**Códigos recebidos:**

- **200** - OK registro;

- **201** - OK KeepAlive;

- **202** - OK para conexão encerrada;

- **400** - Usuário duplicado;

- **401** - Usuário incorreto (com ":" ou com " ");

- **402** - Sala lotada.

**Observações:**

- Caso o jogador entre em outra sala, o mesmo terá TOKENS diferentes;

- Caso o jogador perca a conexão, ao entrar na sala novamente terá outro TOKEN.

**Comment by JeanMotaa** [comment]
**- Requisições Cliente - Servidor:**

**Autenticação cliente:**
	Envio de solicitação de identificação ao servidor para que seja validado e então respondido com um token.
 
Escolha de jogadores:  Usuário registrando presença no ambiente.
**JOGADOR 1**: Visualização do mapa de forma integral(principal).
**JOGADOR 2**: Visualização do mapa de forma reduzida - ir para esquerda e direita.
**JOGADOR 3:** Visualização do mapa de forma reduzida - ir para cima e para baixo.

- Exemplo de requisição:

Cliente { 
```
- “Botão_EscolhaPersonagem1” = "cadastro::player_VisorMapa"
- “Botão_EscolhaPersonagem2” = "cadastro::player_movHorizontal"
- “Botão_EscolhaPersonagem3” = "cadastro::player_movVertical"
```
}

**CASO 1** - Resposta: Successful 
Usuário escolhido livre para jogar 
Servidor {
```
"message: “player_xyz was chosen“, 
“status : 200”
```
  }

**CASO 2** - Resposta: Unsuccessful  
Usuário está tentando conectar na sala, porém servidor não permite por erro de usuário (jogador escolhido duplicado)
Servidor {
```
“message: “duplicate user”, 
“status: 401”
```
}

**- Criação de sala:**
Requisição do jogador principal para que o servidor crie ambientes isolados entre si para se fazer o uso concorrente do mesmo serviço e então liberar o ingressamento de outros participantes

- Exemplo requisição da criação da sala 

Cliente {

`“Botão_Start” = "entrar:Partida"`

}

**CASO 1:** Successful → Sala criada

Servidor {
```
"message: “created room”,
“status : 200"
```
  }

**CASO 2**: Unsuccessful → Sala já foi criada

Servidor {
```
“message: “room already exist”,
“status: 400”
```
}

**- Entrar na sala:**
Outros jogadores recebem requisição para entrarem em uma sala já existente com a permissão do dono da sala(jogador principal)

- Exemplo de requisição:

Cliente {

```
“autor”: player_yz,
“action: “log_in”,
“room”: “room_name”
```

}

**CASO 1**: Successful → Jogador escolhido disponível, acesso permitido

Servidor {
```
"message: “free access”,
“status : 200"
```
  }

**CASO 2**: Unsuccessful → jogador escolhido não disponível, acesso negado

Servidor {

```
“message:  “blocked access”,
“status: 401”
```

}

**CASO 3**: Unsuccessful → jogador escolhido não disponível, lotação de sala.

Servidor {

```
“message:  “crowded room”,
“status: 403”
```

}

**- Convite para um usuário**:
Dono da sala envia requisição para outros jogadores entrarem em uma sala já existente. 

- Exemplo de requisição:

Cliente {

```
“autor”: player_x,
“action: “log_in”,
“room”: “room_name”
```

}

**CASO 1**: Successful → Jogador escolhido disponível, acesso permitido

Servidor {
```
"message: “free access”,
“status : 200"
```
  }
**CASO 2**: Unsuccessful → jogador escolhido não disponível, acesso negado

Servidor {

```
“message:  “blocked access”,
“status: 401”
```

}

**Sair da sala:**
Notificação para sair de uma sala, finalizando sua conexão

- Exemplo de requisição:

Cliente {

```
“autor”: player_xyz,
“action: “log_out”
“room”: “room_name”
```

}

Servidor {

```
“message:  “leaving the room”,
“status: 202”
```

}

**- Negociação de configuração de mídia:**
Usuário ofertando uma configuração de mídia

- Exemplo de requisição

Cliente {

```
“autor”: player_xyz,
“action: “media _offer( )”
```

}

**CASO 1**: Sucessful → Mídia suportada 

Servidor {

```
“message:  “successful media offer”,
“status: 200”
```

}

**CASO 2**: Unsuccessful → Mídia não suportada 

Servidor {
```
“message: “unsuccessful media offer”,
“status: 400 ”
```

}
**- Observações:**

- Mensagem KeepAlive → Mensagem recorrente para verificar se o link entre os dois está operando;
{

```
“message: “KeepAlive”,
“status: 201”
```

}
- Caso o jogador perca conexão, ao entrar na sala novamente terá outro TOKEN;
 
**Códigos recebidos:**
**200 - OK registro;
201 - OK KeepAlive;
202 - OK para conexão encerrada;
400 - Usuário duplicado;
401 - Usuário incorreto (com ":" ou com " ");
403 - Sala lotada.**
